/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostsSlugRouteImport } from './routes/hosts.$slug'
import { Route as HostRegisterRouteImport } from './routes/host.register'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as DashboardReviewRouteImport } from './routes/dashboard_.review'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard_.events.new'
import { Route as DashboardEventsIdEditRouteImport } from './routes/dashboard_.events.$id.edit'
import { Route as DashboardEventsIdCheckInRouteImport } from './routes/dashboard_.events.$id.check-in'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsSlugRoute = HostsSlugRouteImport.update({
  id: '/hosts/$slug',
  path: '/hosts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRegisterRoute = HostRegisterRouteImport.update({
  id: '/host/register',
  path: '/host/register',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewRoute = DashboardReviewRouteImport.update({
  id: '/dashboard_/review',
  path: '/dashboard/review',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/dashboard_/events/new',
  path: '/dashboard/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsIdEditRoute = DashboardEventsIdEditRouteImport.update({
  id: '/dashboard_/events/$id/edit',
  path: '/dashboard/events/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsIdCheckInRoute =
  DashboardEventsIdCheckInRouteImport.update({
    id: '/dashboard_/events/$id/check-in',
    path: '/dashboard/events/$id/check-in',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tickets': typeof TicketsRoute
  '/dashboard/review': typeof DashboardReviewRoute
  '/events/$slug': typeof EventsSlugRoute
  '/host/register': typeof HostRegisterRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/events/$id/check-in': typeof DashboardEventsIdCheckInRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tickets': typeof TicketsRoute
  '/dashboard/review': typeof DashboardReviewRoute
  '/events/$slug': typeof EventsSlugRoute
  '/host/register': typeof HostRegisterRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/events/$id/check-in': typeof DashboardEventsIdCheckInRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tickets': typeof TicketsRoute
  '/dashboard_/review': typeof DashboardReviewRoute
  '/events/$slug': typeof EventsSlugRoute
  '/host/register': typeof HostRegisterRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard_/events/new': typeof DashboardEventsNewRoute
  '/dashboard_/events/$id/check-in': typeof DashboardEventsIdCheckInRoute
  '/dashboard_/events/$id/edit': typeof DashboardEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/my-events'
    | '/sign-in'
    | '/sign-up'
    | '/tickets'
    | '/dashboard/review'
    | '/events/$slug'
    | '/host/register'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/dashboard/events/new'
    | '/dashboard/events/$id/check-in'
    | '/dashboard/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/my-events'
    | '/sign-in'
    | '/sign-up'
    | '/tickets'
    | '/dashboard/review'
    | '/events/$slug'
    | '/host/register'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/dashboard/events/new'
    | '/dashboard/events/$id/check-in'
    | '/dashboard/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/explore'
    | '/my-events'
    | '/sign-in'
    | '/sign-up'
    | '/tickets'
    | '/dashboard_/review'
    | '/events/$slug'
    | '/host/register'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/dashboard_/events/new'
    | '/dashboard_/events/$id/check-in'
    | '/dashboard_/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  MyEventsRoute: typeof MyEventsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TicketsRoute: typeof TicketsRoute
  DashboardReviewRoute: typeof DashboardReviewRoute
  EventsSlugRoute: typeof EventsSlugRoute
  HostRegisterRoute: typeof HostRegisterRoute
  HostsSlugRoute: typeof HostsSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
  DashboardEventsIdCheckInRoute: typeof DashboardEventsIdCheckInRoute
  DashboardEventsIdEditRoute: typeof DashboardEventsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$slug': {
      id: '/hosts/$slug'
      path: '/hosts/$slug'
      fullPath: '/hosts/$slug'
      preLoaderRoute: typeof HostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/register': {
      id: '/host/register'
      path: '/host/register'
      fullPath: '/host/register'
      preLoaderRoute: typeof HostRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/review': {
      id: '/dashboard_/review'
      path: '/dashboard/review'
      fullPath: '/dashboard/review'
      preLoaderRoute: typeof DashboardReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/events/new': {
      id: '/dashboard_/events/new'
      path: '/dashboard/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/events/$id/edit': {
      id: '/dashboard_/events/$id/edit'
      path: '/dashboard/events/$id/edit'
      fullPath: '/dashboard/events/$id/edit'
      preLoaderRoute: typeof DashboardEventsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/events/$id/check-in': {
      id: '/dashboard_/events/$id/check-in'
      path: '/dashboard/events/$id/check-in'
      fullPath: '/dashboard/events/$id/check-in'
      preLoaderRoute: typeof DashboardEventsIdCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  MyEventsRoute: MyEventsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TicketsRoute: TicketsRoute,
  DashboardReviewRoute: DashboardReviewRoute,
  EventsSlugRoute: EventsSlugRoute,
  HostRegisterRoute: HostRegisterRoute,
  HostsSlugRoute: HostsSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
  DashboardEventsIdCheckInRoute: DashboardEventsIdCheckInRoute,
  DashboardEventsIdEditRoute: DashboardEventsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
